manifest:
  remotes:
    - name: zephyrproject-rtos
      url-base: https://github.com/zephyrproject-rtos
    - name: origin
      url-base: https://github.com/PEROVSAT

  projects:
    - name: zephyr
      remote: zephyrproject-rtos
      revision: v4.4.0
      import:
        name-allowlist:
          - cmsis_6
          - cmsis
          - hal_stm32

    - name: mpu6050-driver
      remote: origin
      revision: main

  self:
    path: perovsat-app
    west-commands: dbuild/west-commands.yml
